Controllers/PartnerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Globalization;
using VolunTEENProject.Models;
using VolunTEENProject.Models.Repositories;
using VolunTEENProject.ViewModels.Partner;

namespace VolunTEENProject.Controllers
{
    public class PartnerController : Controller
    {

        private readonly IPartnerRepository _partnerRepository;
        private readonly UserManager<EndUser> _userManager;
        private readonly IConfiguration _config;

        public PartnerController(IPartnerRepository partnerRepository, IConfiguration config, UserManager<EndUser> userManager)
        {
            _partnerRepository = partnerRepository;
            _config = config;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreatePartner()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePartner(CreatePartner model)
        {

            if (ModelState.IsValid)
            {

                Partner newPartner = new Partner
                {
                    PartnerName = model.PartnerName,
                    Email = model.Email,
                    NormalizedEmail = model.Email.ToUpper(),
                    PhoneNumber = model.PhoneNumber,
                    StreetAddress = model.StreetAddress,
                    AddressSecondLine = model.AddressSecondLine,
                    City = model.City,
                    State = model.State,
                    ZipCode = model.ZipCode,
                    CreatedTime = DateTime.Now
                };
                string uploadLocation = ("PartnerLogos/" + model.PartnerName.Replace(" ", "") + "Logo");

                string blobStorageConnection = _config.GetConnectionString("BlobConnection");
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(blobStorageConnection);
                CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
                CloudBlobContainer container = blobClient.GetContainerReference(_config.GetValue<string>("BlobContainerName"));
                CloudBlockBlob blockBlob = container.GetBlockBlobReference(uploadLocation);
                try
                {
                    await using (var data = model.PartnerLogo.OpenReadStream())
                    {
                        await blockBlob.UploadFromStreamAsync(data);
                    }
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", "File could not be uploaded at this time. Please try again or contact an administrator.");
                    return View(model);
                }
                newPartner.PartnerLogo = uploadLocation;

                _partnerRepository.CreatePartner(newPartner);

                ViewBag.IsSuccessful = "This was successful";
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        public IActionResult AddUser()
        {
            
            ViewBag.UserList = CreateUserList();
            ViewBag.PartnerList = CreatePartnerList();

            return View();
        }

        [HttpPost]
        public IActionResult AddUser(AddUser model)
        {

            if (ModelState.IsValid)
            {

                var toBeAdded = _userManager.Users.FirstOrDefault(u => u.Id == model.userID);
                var toBeUpdated = _partnerRepository.GetPartners().FirstOrDefault(p => p.PartnerID == Int32.Parse(model.partnerID));

                _partnerRepository.AddUser(toBeAdded, toBeUpdated);

                return RedirectToAction("Index", "Home");

            }

            ViewBag.UserList = CreateUserList();
            ViewBag.PartnerList = CreatePartnerList();

            return View();
        }

        ///**************************************************************///
        ///*************************Functions****************************///
        ///**************************************************************///

        public List<SelectListItem> CreatePartnerList()
        {

            List<SelectListItem> partnerList = new List<SelectListItem>();

            partnerList.Add(new SelectListItem
            {
                Text = "Select a Partner to be added to",
                Value = "",
                Disabled = true,
                Selected = true
            });

            foreach (var partner in _partnerRepository.GetPartners())
            {
                SelectListItem selectListItem = new SelectListItem
                {
                    Value = partner.PartnerID.ToString(),
                    Text = partner.PartnerName
                };

                partnerList.Add(selectListItem);
            }

            return partnerList;
        }

        public List<SelectListItem> CreateUserList()
        {
            List<SelectListItem> userList = new List<SelectListItem>();

            userList.Add(new SelectListItem
            {
                Text = "Select a User to Add",
                Value = "",
                Disabled = true,
                Selected = true
            });

            foreach (var user in _userManager.Users)
            {
                SelectListItem selectListItem = new SelectListItem
                {
                    Value = user.Id,
                    Text = (user.FirstName + " " + user.LastName)
                };

                userList.Add(selectListItem);
            }

            return userList;

        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VolunTEENProject.Models;
using VolunTEENProject.ViewModels.Role;

namespace VolunTEENProject.Controllers
{
    public class RoleController : Controller
    {

        private readonly RoleManager<Role> _roleManager;

        public RoleController(RoleManager<Role> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult CreateRole() { 
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRole role)
        {
            if (ModelState.IsValid)
            {

                Role newRole = new Role()
                {
                    Name = role.Name,
                    RoleDescription= role.Description,
                    IsPartnerRole= role.IsPartnerRole,
                };

                var result = await _roleManager.CreateAsync(newRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index","Home");
                } 

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(role);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VolunTEENProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VolunTEENProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VolunTEENProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-row-reverse mr-3">
                        @*
                        <li class="nav-item">
                            <a class="nav-link" asp-action="CreateRole" asp-controller="Role">Create Role</a>
                        </li>
                        *@
                        @*
                        <li class="nav-item">
                            <a class="nav-link" asp-action="CreateEndUser" asp-controller="Account">Create EndUser</a>
                        </li>
                        *@
                        @*
                        <li class="nav-item">
                            <a class="nav-link" onclick="location.href='@Url.Action("EndUserDetails", "Account", new { EndUserId = "4062e723-cba3-4686-b894-7eb19bfe2deb" })'">EndUser Details</a>
                        </li>
                        *@
                        @*
                        <li class="nav-item">
                            <a class="nav-link" asp-action="CreatePartner" asp-controller="Partner">Create Partner</a>
                        </li>
                        *@
                        <li class="nav-item">
                            <a class="nav-link" asp-action="AddUser" asp-controller="Partner">AddUser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Login" asp-controller="Home">Login</a>
                        </li>
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li>
                                <a class="nav-link">Hello, @User.Identity.Name</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VolunTEENProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>